//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanelKey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Panel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Panel()
        {
            this.Tbl_PanelKey = new HashSet<Tbl_PanelKey>();
        }
    
        public int PanelId { get; set; }
        public string PanelName { get; set; }
        public Nullable<int> PanelStatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PanelKey> Tbl_PanelKey { get; set; }
    }
}
