//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanelKey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Key
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Key()
        {
            this.Tbl_PanelKey = new HashSet<Tbl_PanelKey>();
            this.Tbl_UserKey = new HashSet<Tbl_UserKey>();
        }
    
        public int KeyId { get; set; }
        public string KeyName { get; set; }
        public string KeyDescription { get; set; }
        public Nullable<int> KeyStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PanelKey> Tbl_PanelKey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UserKey> Tbl_UserKey { get; set; }
    }
}
